name: Standalone build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Build OpenTTD
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install imagemagick -y
          make

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nodusttd
          path: |
            dist/openttd.js
            dist/openttd.data
            dist/openttd.wasm
            dist/index.html